### ISSUE TITLE
token is undefined

### ISSUE THREAD

**Issue by Maygs** [tinderjs/tinderauth#3]
When I run the following:

```
var tinderauth = require('tinderauth');

tinderauth.default().then(function(response){
  var token = response.token;
  var profile_id = response.profile_id;
  console.log(token, profile_id);
});
```

It returns "undefined, '101010101010'

(Where 1010101010 is the correct facebook ID)

Any idea what is going on?

**Comment by Maygs** [comment]
Wait I believe may have understood this library wrong.. I thought it was able to create a tinder account for that facebook profile and get its token? I guess it just gets the token and does not actually create the tinder account?

**Comment by Maygs** [comment]
Okay, all sorted. The problem was I did not validate the email attached to the account (which was not letting me create an account and retrieve a token). Service works as it should. Thanks

**Comment by mayeaux** [comment]
Have never tried it to create an account from scratch, but it works for you?

**Comment by Maygs** [comment]
Nope but I can automate it with Selenium and then use tinderauth to get the token.

**Comment by mayeaux** [comment]
Did you end up writing the script for it? Maybe you want to add it to the `tinderjs` org?
